channels:
  - anaconda
  - estnltk
  - conda-forge
  - defaults
dependencies:
  - python=3.6.6
  - pytorch=1.3.1=cuda92py36hb0ba70e_0
  - numpy==1.17.4=py36hc1035e2_0
  - librosa==0.6.3
  - scipy==1.5.2
  - inflect==4.1.0
  - matplotlib==3.3.2
  - estnltk=1.6.5beta=3.6
  - tensorboardx=2.1
  - Unidecode==1.0.22
  - pillow
  - cudatoolkit